[features]
seeds = false
skip-lint = false

[programs.localnet]
poirl = "Adqu9U29r9oQHiBxvykpw8MnYMSbbBwC2YH4z9shbdfq"
[programs.devnet]
poirl = "Adqu9U29r9oQHiBxvykpw8MnYMSbbBwC2YH4z9shbdfq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "../test_dir/wallets/program_auth.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
putArxOnChain = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 devnetScripts/putArxOnChain.ts"