[features]
seeds = false
skip-lint = false

[programs.localnet]
poirl = "5yXZS9y1HQ2Ndu66fogKi7tzJbJZeWGGLTNYX7uc8x3o"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "../test_dir/wallets/program_auth.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
